### ISSUE TITLE
Improper stack config causes stack module to poorly exit terraform

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/terraform-yaml-stack-config#25]
## Describe the Bug

This stack configuration: 

```yaml
import:
  - catalog/globals

vars:
  environment: automation

components:
  terraform:
    # account-settings:
```

causes this error: 

![image](https://user-images.githubusercontent.com/1392040/115468482-6134b800-a1f0-11eb-9ed9-8643706e1772.png)

## Expected Behavior

I expect to get a runtime error that is useful in debugging what happened without enabling `TF_LOG=1`

## Steps to Reproduce
1. Use the above stack configuration.
2. Pass it to the spacelift module or however else you consume terraform-yaml-stack-config
3. Try a plan
4. 💥 

## Screenshots

Here is the full error that I found after enabling `TF_LOG`: 

![image](https://user-images.githubusercontent.com/1392040/115468733-bd97d780-a1f0-11eb-8497-7ccb5850a080.png)
